### ISSUE TITLE
How should value-unit pairs be defined in config files?

### ISSUE THREAD

**Issue by johnjasa** [NREL/GreenHEART#52]
We should allow config files to explicitly specify values and units for any parameter. This means that someone could identify plant size in kW or MW, for example.

Should they be provided as tuples:
```
technologies:  
  battery:
      model: "pysam"
        chemistry: "LFPGraphite"
        system_capacity: (100000, kWh)
        system_capacity: (100000, kW)
        minimum_SOC: (20.0, percent)
        maximum_SOC: (100.0, percent)
        initial_SOC: (90.0, percent)
```

or as more explicit value-unit entries:
```
technologies:  
  battery:
      model: "pysam"
        chemistry: "LFPGraphite"
        system_capacity:
          value: 100000
          units: kWh
        system_capacity:
          value: 100000
          units: kW
        minimum_SOC:
          value: 20.
          units: percent
        maximum_SOC:
          value: 100.
          units: percent
        initial_SOC:
          value: 90.
          units: percent
```

A mild wrinkle is that when defining more complex values (arrays or lower/upper bound combos for optimization) we might need more precision in the definition. Which one is more intuitive?

```
design_variables:
  solar:
    plant_size:
      flag: True
      bounds: ((50., 150.), kW)
```

or
```
design_variables:
  solar:
    plant_size:
      flag: True
      lower: 50.
      upper: 150.
      units: kW
```
