### ISSUE TITLE
Detail: can specify feedstock region for site (used in profast feedstocks)

### ISSUE THREAD

**Issue by johnjasa** [NREL/GreenHEART#67]
Could do US avg or specify region; ProFAST costs might vary per-region (water)

Originally ID'd by @elenya-grant

**Comment by elenya-grant** [comment]
In ProFAST you can set the feedstock cost for common feedstocks (electricity, coal, diesel, water, natural gas) by specifying a feedstock region or 'US Average' as the cost (rather than a dollar amount). The 9 feedstock regions are comprised of multiple states. Since we don't specify the state of the site, and the `feedstock` component requires a cost input, it may not be feasible to add this in easily. However, I could see this being used as a pre-processing tool to get specific feedstock costs from the ProFAST feedstock cost data sheet.

Below is a summary of feedstock regions and the states within them:

```yaml
Mountain: ['Idaho','Montana','Wyoming','Utah','Arizona','New Mexico','Nevada','Colorado']
Pacific: ['Oregon','Washington','California']
East North Central: ['Michigan','Indiana','Illinois','Wisconsin','Ohio']
West North Central: ['North Dakota','South Dakota','Minnesota','Nebraska','Kansas','Iowa','Missouri']
West South Central: ['Oklahoma','Texas','Arkansas','Louisiana']
East South Central: ['Mississippi','Alabama','Tennessee','Kentucky']
South Atlantic: ['Florida','Georgia','South Carolina','North Carolina','Virginia','West Virginia','Maryland','Delaware']
New England: ['Connecticut','Rhode Island','Vermont','New Hampshire','Massachusetts','Maine']
Middle Atlantic: ['New York','Pennsylvania','New Jersey']
```
