### ISSUE TITLE
How should we handle partial financial stackups at the config level?

### ISSUE THREAD

**Issue by johnjasa** [NREL/GreenHEART#74]
# How should we handle partial financial stackups at the config level?

The prior version of GreenHEART had a partial financial stackup calculation to calculate LCOH which was then fed into the steel model.
The steel model had its own financial computations.
Nominally, we want to handle these cases in a general and understandable way that the user can configure.

How should we go about this?

## Proposed solution

In the new GreenHEART playground I've implemented this in a somewhat clunky but effective way.
Each technology's financial model can belong to a group.
All members of that group are used in a financial stackup.
In the following example, HOPP and the electrolyzer are in group 1 so LCOH can be calculated and passed to group 2's steel model.

```
technologies:
  hopp:
    performance_model:
      model: "hopp"
      config: !include hopp_config.yaml
    cost_model:
      model: "hopp"
    financial_model:
      group: 1
  electrolyzer:
    performance_model:
      model: "eco_pem_electrolyzer"
    cost_model:
      model: "eco_pem_electrolyzer"
    financial_model:
      group: 1
    details:
<...>
  steel:
    performance_model:
      model: "steel"
    cost_model:
      model: "steel"
    financial_model:
      group: 2
```

Is this the best approach?
What would you change or how would you present this to users?
Is this type of modular partial stackup not necessary?
